# Generated by Django 4.2.16 on 2024-11-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_essence', '0002_rename_date_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Courses', 'Main Courses'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=100)),
            ],
        ),
    ]
