# Generated by Django 4.2.16 on 2024-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_essence', '0004_menuitem_currency_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
