# Generated by Django 4.2.16 on 2024-11-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_essence', '0006_rename_guests_reservation_guest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
