# Generated by Django 4.2.16 on 2024-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_essence', '0007_reservation_first_name_reservation_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
