# Generated by Django 4.2.16 on 2024-11-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine_essence', '0008_reservation_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
    ]
